/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiPublicCvRouteImport } from './routes/api/public/cv'
import { Route as ApiPublicPhotoRouteImport } from './routes/api/public/photo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCvRoute = ApiPublicCvRouteImport.update({
  id: '/api/public/cv',
  path: '/api/public/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPhotoRoute = ApiPublicPhotoRouteImport.update({
  id: '/api/public/photo',
  path: '/api/public/photo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/public/cv': typeof ApiPublicCvRoute
  '/api/public/photo': typeof ApiPublicPhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/public/cv': typeof ApiPublicCvRoute
  '/api/public/photo': typeof ApiPublicPhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/public/cv': typeof ApiPublicCvRoute
  '/api/public/photo': typeof ApiPublicPhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/api/public/cv' | '/api/public/photo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/api/public/cv' | '/api/public/photo'
  id: '__root__' | '/' | '/admin' | '/api/public/cv' | '/api/public/photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiPublicCvRoute: typeof ApiPublicCvRoute
  ApiPublicPhotoRoute: typeof ApiPublicPhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cv': {
      id: '/api/public/cv'
      path: '/api/public/cv'
      fullPath: '/api/public/cv'
      preLoaderRoute: typeof ApiPublicCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/photo': {
      id: '/api/public/photo'
      path: '/api/public/photo'
      fullPath: '/api/public/photo'
      preLoaderRoute: typeof ApiPublicPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiPublicCvRoute: ApiPublicCvRoute,
  ApiPublicPhotoRoute: ApiPublicPhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
